name: Deploy to GCP when index.html is modified

on:
  push:
    branches:
      - master  # 當 main 分支有更新時觸發
    paths:
      - '/home/git_test/index.html'  # 當此文件被修改時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
       
      - name: Check source file
        run: ls -al var/www/index.html
          
      - name: Set up GCP credentials
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # GCP 項目 ID
          service_account_key: ${{ secrets.CI_CD_TEST }}  # 服務帳戶金鑰

      - name: Deploy to GCP (e.g., Compute Engine)
        run: |
          echo "Deploying index.html to GCP Compute Engine"
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no /var/www/index.html testGCP@35.221.185.100:/var/www/index.html
